### PR TITLE
Added Kafdrop link

### PR DESCRIPTION
**Pull request by ekoutanov**
Refined the Kafdrop link to include the repository for legacy brokers as well as the 3.x repo for newer brokers

### CODE REVIEW

**Comment by dharmeshkakadia** [comment]
I think putting both of them on a single line makes sense. Something like 

* [Kafdrop](https://github.com/obsidiandynamics/kafdrop) – web UI Kafka brokers. For version older than 0.10.0 use [Kafdrop 2.x](https://github.com/HomeAdvisor/Kafdrop) fork.


What do you think?

**Comment by dharmeshkakadia** [comment]
@ekoutanov You think you can make this change?

**Comment by ekoutanov** [comment]
OK i will

**Comment by ekoutanov** [comment]
Done @dharmeshkakadia

**Comment by dharmeshkakadia** [comment]
Thanks !

**Pull request merged**
